### ISSUE TITLE
Hardware flow control support

### ISSUE THREAD

**Issue by gsk-reddy** [gohai/p5.webserial#10]
this feature would make this library capable of uploading firmware to ESP32, STM32, arduino and also for communication with RS485 

edit:
webserial api for this:
https://developer.chrome.com/docs/capabilities/serial#signals

`flowControl: 'hardware'` should be passed in options when opening serial port
then new functions can be added to read/write DTR, RTS, CTS etc.

**Comment by gohai** [comment]
@GSK-Reddy Do you have a suggestion how functions to this end should be called - e.g. how other libraries name them?

I am not sure whether `flowControl: hardware` is necessary for being able to assert those DTR, RTS lines, btw. Happy to look into it.

**Comment by gohai** [comment]
@GSK-Reddy DTR and RTS are easy - could you try out this change: https://github.com/gohai/p5.webserial/commit/e929ece8bb80598ccbed7137ba62cffdf32a2ed5

**Comment by gohai** [comment]
Merged.
