### ISSUE TITLE
Polyfill for Android chrome?

### ISSUE THREAD

**Issue by hpssjellis** [gohai/p5.webserial#4]
Is there any interest to try to get P5-webserial.js working with Polyfill?   

https://github.com/google/web-serial-polyfill

I used to have it working about 6 months ago, but it since seems to have broken with the latest Chrome.

**Comment by gohai** [comment]
Thanks for your suggestion @hpssjellis - could you elaborate a bit? (Chrome on Android supports WebUSB but not WebSerial? You had the polyfill working as of 6 month ago but it doesn't anymore?) Thank you - not familiar with Android these days, but I'd love to help support it if feasible.

**Comment by hpssjellis** [comment]
@gohai thanks for the reply. If you have an arduino then this website with sketch should work for you on a desktop/laptop computer.    https://hpssjellis.github.io/my-examples-of-arduino-webUSB-webSerial/public/webserial-and-polyfill.html

I made the site before even finding out that p5.webserial was a thing.  On the page are links to the arduino sketch which is fairly simple  https://hpssjellis.github.io/my-examples-of-arduino-webUSB-webSerial/public/arduino04-webserial.txt

```
#include <Arduino.h> // Only needed for https://platformio.org/

String readString;

int myDelay = 5000;   // non-block delay in milliseconds
unsigned long myStart; 
int serialMessage = 1;
int myCount=48;      //48 = ascii 0,    58 ascii 9

void setup() {
  Serial.begin(9600);
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, HIGH);   // onboard LED, HIGH = off
  
  myStart = millis();   // set delay
  randomSeed(analogRead(A0));  // AO pin on XIAO does not have to be connected to anything

}

void loop() {

  if ( (millis() - myStart ) >= myDelay) {       
     myStart = millis();      //  reset the delay time
     myCount++;
     if (myCount >= 58){ // 48 = ascii 0,    58 ascii 9
       myCount = 48;
     }       
     //char myChar = (char)myCount;      
     byte myChar = (byte)myCount;    
     Serial.write(myChar);  
   }

  

  while (Serial.available()) {
    delay(3);  
    char c = Serial.read();
    readString += c; 
  }

  if (readString.length() > 0) {
    Serial.println(readString);

    if (readString == "a"){
      digitalWrite(LED_BUILTIN, LOW); //onboard LED LOW = on
      Serial.println("LED ON");
    }
    if (readString == "b"){
      digitalWrite(LED_BUILTIN, HIGH);
      Serial.println("LED OFF");
    }
    readString="";
  } 
}

  ```

.

.


For the connected webpage, see first link above,  I activate webSerial [here](https://github.com/hpssjellis/my-examples-of-arduino-webUSB-webSerial/blob/eaffed647bdf3d93a57a740a1c9b3c2fc835502f/public/webserial-and-polyfill.html#L35-L38)

 ```
document.getElementById('connectButton').addEventListener('click', () => {
  if (navigator.serial) {
    connectSerial();
  } else {
    document.getElementById('myDiv01').innerHTML = 'Web Serial API not supported. Switching to Polyfill<br>'
    myPoly()

  }
});
```

Note in the above code if webSerial does not work for Desktop or Laptop it auto loads myPoly() whose code is [here](https://github.com/hpssjellis/my-examples-of-arduino-webUSB-webSerial/blob/eaffed647bdf3d93a57a740a1c9b3c2fc835502f/public/webserial-and-polyfill.html#L134-L158) 


and that code worked  6 months ago on Android, but now does not work. I believe IOS does not have a way to get webSerial working which is too bad, hopefully in the future webSerial will work on all mobile devices.

I teach Machine Learning to High school students. All of this would be much easier with WebSerial working on Mobile and Desktop/Laptop. 


My Github Profile is at
https://github.com/hpssjellis


If you want to get WebSerial working on Android for P5.webserial I would help where I can. It would be nice for me to use your webserial since P5 is much better known than any of my code.

**Comment by gohai** [comment]
Hi @hpssjellis 

I tried incorporating the polyfill. I lack a way of testing it - if you can, please try [this sketch](https://editor.p5js.org/gohai/sketches/9Bdb7fU5k), or the library in the `webusb-polyfill` branch (this isn't published yet). Thanks in advance!

**Comment by hpssjellis** [comment]
@gohai on desktop it does seem to connect but the serial print is getting overlapped.   
![image](https://github.com/gohai/p5.webserial/assets/5605614/b319757a-c853-41b3-973c-066083223773)

A couple of issues. 
1. I have just loaded my Arduino code so not really sure what code I should use to run your app. Instead of the "Hello" button more useful would be a text box with button so we can send any command to the Arduino. 
2. I also can't test polyfill. My new Android phone does not run it, the only phones I have found that consistently run polyfill are Google Pixel phones as a few of my students have them. I may try to purchase an old one just for testing.


My site, with webSerial and polyfill does auto switch between desktop/laptop webSerial and Android phone using polyfill I just don't have the right phone.

my Site   https://hpssjellis.github.io/webMLserial/public/a05-resistor/a05-resistor-index.html

my Arduino code   https://hpssjellis.github.io/webMLserial/public/a05-resistor/a05-resistor.txt

**Comment by hpssjellis** [comment]
@gohai are you connected with the ML5.js project? I think p5.js has a form of webSerial working. I just found out about [mljs.org](https://ml5js.org/about) which looks similar (much more professional) to what I want to do, except with Arduino connectivity not just tensorflowJS.

**Comment by gohai** [comment]
Hi @hpssjellis 

- The Arduino code for the test application is `examples/basic/basic_arduino`. This wasn't to be a full-fledged terminal application - instead just demonstrating how to use this library...
- The `webusb-polyfill` branch (and the sketch I linked to) will also automatically try WebUSB whenever WebSerial isn't available. I just don't have a way to test this presently...

As for the ML5 project: I am peripherally involved - not sure how this relates to serial communication, though? WebSerial with this library works quite fine, as far as I am aware of - are you specifically talking about Android support?

**Comment by hpssjellis** [comment]
> As for the ML5 project: I am peripherally involved - not sure how this relates to serial communication, though? WebSerial with this library works quite fine, as far as I am aware of - are you specifically talking about Android support?

I put in a feature request at ml5js to see if they can combine webSerial/polyfill to use sensor data for machine learning tensorflowjs training. Here is the link   [https://github.com/ml5js/ml5-next-gen/issues/9](https://github.com/ml5js/ml5-next-gen/issues/9) I was going to mention you but thought I would ask you first. Please reply to it if you have any suggestions.

I think p5js has a way to connect Arduinos to web pages using webSerial (I don't think it has the Android polyfill backup), and ml5js makes machine learning models using tensorflowJS but I don't think anyone has put the 2 concepts together.

**Comment by hpssjellis** [comment]
@gohai I found your arduino code. I did not realize you were working from p5.js I thought you were from google webserial.  

Something that would be really useful would be a way to tell which Android phones support polyfill without having to have an Arduino with the special cable to test it. 


Here is the Arduino code that runs with your example at [https://editor.p5js.org/gohai/sketches/9Bdb7fU5k](https://editor.p5js.org/gohai/sketches/9Bdb7fU5k)


```
int lines = 0;
unsigned long lastSent = 0;

void setup() {
  Serial.begin(57600);
}

void loop() {
  if (Serial.available() > 0) {
    String input = Serial.readStringUntil('\n');
    if (input.length() > 0) {

      // this would be the place to parse, 
      // and act upon the message from the
      // computer

      lines++;
    }
  }

  unsigned long now = millis();
  if (now-lastSent > 2000) {
    Serial.print("Hello! I heard you ");
    Serial.print(lines);
    Serial.println(" times");
    lastSent = now;
  }
}
```

**Comment by hpssjellis** [comment]
@gohai Your Arduino code works much better with your setup on Desktop.

![image](https://github.com/gohai/p5.webserial/assets/5605614/02c68030-4c6e-4848-bd7e-5d8bf368d5a6)


I will try to find a Google Pixel phone to test it on Android.

**Comment by hpssjellis** [comment]
hey @gohai Your code connected with the Arduino PortentaH7  using a double sided usb-C cable

![image](https://github.com/gohai/p5.webserial/assets/5605614/ef1bdbae-e426-4665-808b-55f43ddb2c51)



2 interesting things. My Seeedstudio XIAO did not connect and my special cable USB-micro-to USB OTG did not work (although I think it has worked in the past.)

![image](https://github.com/gohai/p5.webserial/assets/5605614/8712adb0-80ca-48b7-8e31-0f254b28c906)
)


The XIAO is an important connection since it is very cheap ($5 USD).  When I started working with WebSerial their was a product ID that was entered. My latest code does not use that filter. Does your code or p5.js code have an Arduino only filter?

**Comment by gohai** [comment]
@hpssjellis Happy to hear!

And yes, there's an filter for Arduino(-like) devices. Remove the first parameter (`'Arduino'`) from `port.open()` inside the p5.js sketch.

**Comment by hpssjellis** [comment]
Makes sense since it the XIAO does work on my Code at [here](https://hpssjellis.github.io/my-examples-of-arduino-webUSB-webSerial/public/webserial-and-polyfill.html)  

By the way that cell phone was an old Google Pixel V2.

**Comment by gohai** [comment]
Thank you @hpssjellis. I merged the branch and published a new version to npm. In a few hours the WebUSB fallback should be available everywhere.

**Comment by hpssjellis** [comment]
And yes without the name Arduino it worked on the XIAO

![image](https://github.com/gohai/p5.webserial/assets/5605614/a894245c-d133-4505-9052-a17538a76ffc)

**Comment by hpssjellis** [comment]
Nice working with you @gohai any chance you know any machine learning and want to take Arduino connectivity a step farther.  I closed this issue as completed.
