### ISSUE TITLE
opened function doesn't work as expected

### ISSUE THREAD

**Issue by juanferfranco** [gohai/p5.webserial#6]
This part of code in opened function:

```javascript
return (this.port instanceof SerialPort && this.port.readable !== null);
```
this.port has a reference to the native SerialPort, but in this scope this.port instanceof SerialPort is false because it uses the definition of SerialPort in p5.webserial.js.  One possible solution to use the native definition is 

```javascript
opened() {
  const NativeSerialPort = window.SerialPort;
  return (this.port instanceof NativeSerialPort && this.port.readable !== null);
}
```

Thanks for your code.

**Comment by gohai** [comment]
Thank you for taking the time to report - I hope this fixes it. Pushed out to npm as `1.0.6`.
